<?php
//dn lop cylinder ke thua lop circle
include_once('Circle.php');
class Cylinder extends Circle {
    public $height;
    //dn ham khoi tao
    public function __construct($name, $radius, $height)
    {
        parent::__construct($name, $radius);
        $this->height = $height;
    }
    //dn ham tinh toan
    public function calculateArea()
    {
        return parent::calculateArea() *2 + parent::calculatePerimeter() * $this->height; // TODO: Change the autogenerated stub
    }

    public function calculateVolume()
    {
        return parent::calculateArea() * $this->height;
    }
}